//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RICONS.DataServices.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaborate
    {
        public int Id { get; set; }
        public int NguoiDi { get; set; }
        public string TieuDe { get; set; }
        public System.DateTime TuNgay { get; set; }
        public System.DateTime DenNgay { get; set; }
        public string NoiCongTac { get; set; }
        public string MoTa { get; set; }
        public string EmailNguoiDuyet { get; set; }
        public bool DaDuyet { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
    }
}
