//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RICONS.DataServices.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructionMeeting
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string GioHop { get; set; }
        public int Status { get; set; }
        public int LoaiCuocHop { get; set; }
        public string ThanhPhanThamDu { get; set; }
        public string FileDinhKem { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int GiamDoc { get; set; }
        public int CongTruong { get; set; }
    }
}
