//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RICONS.DataServices.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContext : DbContext
    {
        public DBContext()
            : base("name=DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Collaborate> Collaborates { get; set; }
        public virtual DbSet<m_donvi_chucdanh> m_donvi_chucdanh { get; set; }
        public virtual DbSet<m_donvi_phongban> m_donvi_phongban { get; set; }
        public virtual DbSet<m_donvi_thongtingiamdoc> m_donvi_thongtingiamdoc { get; set; }
        public virtual DbSet<m_taikhoan> m_taikhoan { get; set; }
        public virtual DbSet<WeedMeeting> WeedMeetings { get; set; }
        public virtual DbSet<ConstructionMeeting> ConstructionMeetings { get; set; }
    }
}
