//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RICONS.DataServices.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_donvi_chucdanh
    {
        public int machucdanh { get; set; }
        public string tengiaodich { get; set; }
        public string tenchucdanh { get; set; }
        public string xoa { get; set; }
        public Nullable<int> nguoitao { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<int> nguoihieuchinh { get; set; }
        public Nullable<System.DateTime> ngayhieuchinh { get; set; }
        public string ghichu { get; set; }
    }
}
