//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RICONS.DataServices.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_donvi_thongtingiamdoc
    {
        public int mathongtin { get; set; }
        public string hovaten { get; set; }
        public string email { get; set; }
        public string xoa { get; set; }
    }
}
