//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RICONS.DataServices.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_donvi_phongban
    {
        public int madonvi { get; set; }
        public string maphongban { get; set; }
        public string tenphongban { get; set; }
        public string xoa { get; set; }
        public Nullable<int> nguoitao { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<int> nguoihieuchinh { get; set; }
        public Nullable<System.DateTime> ngayhieuchinh { get; set; }
        public string ghichu { get; set; }
        public string email { get; set; }
        public string hovaten { get; set; }
        public Nullable<int> thuocquanly { get; set; }
        public string hotenquanly { get; set; }
        public string sodienthoai { get; set; }
        public Nullable<int> phongban_congtruong { get; set; }
        public Nullable<int> thuocquanly1 { get; set; }
        public string hotenquanly1 { get; set; }
        public string ghichu1 { get; set; }
        public Nullable<int> thuocquanly2 { get; set; }
        public string hotenquanly2 { get; set; }
        public string ghichu2 { get; set; }
    }
}
