//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RICONS.DataServices.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_taikhoan
    {
        public int mataikhoan { get; set; }
        public string manhansu { get; set; }
        public string tendangnhap { get; set; }
        public string thudientu { get; set; }
        public string matkhau { get; set; }
        public string hoten { get; set; }
        public string gioitinh { get; set; }
        public string diachi { get; set; }
        public string sodienthoai { get; set; }
        public string tenhinh { get; set; }
        public string extensionfile { get; set; }
        public string filecontenttype { get; set; }
        public byte[] binarydata { get; set; }
        public Nullable<int> madonvi { get; set; }
        public string is_ada { get; set; }
        public string kichhoat { get; set; }
        public string xoa { get; set; }
        public Nullable<int> nguoitao { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<int> nguoihieuchinh { get; set; }
        public Nullable<System.DateTime> ngayhieuchinh { get; set; }
        public string maphongban { get; set; }
        public string machucdanh { get; set; }
        public string grouptk { get; set; }
        public string chucdanhkpi { get; set; }
        public string phongban_congtruong { get; set; }
        public string chamcong { get; set; }
    }
}
