//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RICONS.DataServices.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeedMeeting
    {
        public int macuochop { get; set; }
        public int matuan { get; set; }
        public string giohop { get; set; }
        public string ngayhop { get; set; }
        public Nullable<int> phonghop { get; set; }
        public string lydobuoihop { get; set; }
        public string thanhphanthamdu { get; set; }
        public string caplanhdao { get; set; }
        public string noidungcuochop { get; set; }
        public string uploadfile { get; set; }
        public string tenfile { get; set; }
        public string xoa { get; set; }
        public Nullable<int> nguoitao { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<int> nguoihieuchinh { get; set; }
        public Nullable<System.DateTime> ngayhieuchinh { get; set; }
        public string maphongban { get; set; }
        public Nullable<int> loaicuochop { get; set; }
    }
}
