var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "ddMMyyyy",
            "fulldayshow": "d L, yyyy",
            "fulldayvalue": "dd/MM/yyyy",
            "Md": "W, d/M",
            "Md3": "d L",
            "separator": "/",
            "year_index": 2,
            "month_index": 1,
            "day_index": 0,
            "day": "d",
            "sun": "cn",
            "mon": "thứ 2",
            "tue": "thứ 3",
            "wed": "thứ 4",
            "thu": "thứ 5",
            "fri": "thứ 6",
            "sat": "thứ 7",
            "jan": "tháng 1",
            "feb": "tháng 2",
            "mar": "tháng 3",
            "apr": "tháng 4",
            "may": "tháng 5",
            "jun": "tháng 6",
            "jul": "tháng 7",
            "aug": "tháng 8",
            "sep": "tháng 9",
            "oct": "tháng 10",
            "nov": "tháng 11",
            "dec": "tháng 12"
        },
        "no_implemented": "No implemented yet",
        "to_date_view": "Xem sự kiện ngày được chọn",
        "i_undefined": "Undefined",
        "allday_event": "Cả ngày",
        "repeat_event": "Repeat event",
        "time": "Thời gian",
        "event": "Sự kiện",
        "location": "Địa điểm",
        "participant": "Participant",
        "get_data_exception": "Exception when getting data",
        "new_event": "Tạo mới sự kiện",
        "confirm_delete_event": "Do you confirm to delete this event? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Lỗi! Dữ liệu không đúng định dạng.",
        "invalid_title": "Tiêu đề không được để trống hoặc chứa ký tự đặc biệt ($<>)",
        "view_no_ready": "View is not ready",
        "example": "e.g., meeting at room 107",
        "content": "What",
        "create_event": "Tạo sự kiện",
        "update_detail": "Chỉnh sửa sự kiện",
        "click_to_detail": "Xem chi tiết",
        "i_delete": "Xóa",
        "day_plural": "days",
        "others": "Khác",
        "item": ""
    }
});
